application:
  SENTRY_DSN: ""
  
  TELEGRAM_TOKEN: ""
  TELEGRAM_TARGET_ID: 0

  S3_BUCKET_NAME: ""
  S3_BOARD_FOLDER: ""

  USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
